### ISSUE TITLE
return code 247

### ISSUE THREAD

**Issue by vzupan3** [broadinstitute/warp#1278] opened 2024-05-12 08:03 UTC
Hi! 
When running ExomeGermlineSingleSample_v3.1.19 on local machine I get an error:
Job VariantCalling.HaplotypeCallerGATK4:2:1 exited with return code 247 which has not been declared as a valid return code.
I tried to bring down # of scatters and try to modify CreateSequenceGroupingTSV task line 49 from "\n" to "\t" leading to a single row/group, leading to single shard/scatter, but that did not resolve the problem.

[stderr.zip](https://github.com/broadinstitute/warp/files/15285455/stderr.zip).

**Comment by adamnovak** [comment] 2024-09-16 19:09
I think the problem is this snippet, where `free` is used to measure total installed system memory, and then the memory reported is assumed to all be available to the task, and Java is asked to use almost all of it.

https://github.com/broadinstitute/warp/blob/fe21c077ffc9c48ae7368e44bb7f6e88ce303b24/tasks/broad/GermlineVariantDiscovery.wdl#L124-L132

This approach can only work in the one-VM-per-task setup used by Cromwell in GCP. If multiple tasks are run on one machine, or even if a task is run on a machine that has other concurrent users or processes using memory, this will set Java to use more memory than is actually available. In general this is likely to be more than the WDL `runtime` section has licensed the task to use.

The `free` command [is *not* able to measure the memory limit of a Slurm job or of a Singularity or Docker container, or of any other form of cgroup confinement](https://forums.docker.com/t/docker-memory-limit-does-not-show-inside-the-container/141503/2); it only reports the memory on the host system. I don't think Cromwell or any other WDL runner injects a container or job-aware `free`.

**Comment by jessicaway** [comment] 2024-10-17 15:24
Hi @adamnovak, 
That is likely the issue. These pipelines are written and optimized for cloud execution, unfortunately they do not always translate well to local or HPC environments. The code is all open source, so feel free to fork and edit as needed to run in your preferred environment. 
Closing this since the issue is understood and will not be addressed in Warp at this time.

**Closed by jessicaway** 2024-10-17 15:24 UTC
