### ISSUE TITLE
Test files still inaccessible

### ISSUE THREAD

**Issue by kalong2** [broadinstitute/warp#798] opened 2022-08-16 17:18 UTC
I am trying to utilize the Whole Genome Germline Single Sample pipeline, so I am first trying the test files provided with package.

As posted in another thread in 2021, the test files are inaccessible. They are unable to access files that are supposed to be under "broad-gotc-test-storage". 

I would really appreciate any help with this.

**Comment by jessicaway** [comment] 2022-09-08 15:16
Hi @kalong2, apologies for the slow reply. This is something we are working in, hopefully we will have an update on progress soon!

**Comment by kevinpalis** [comment] 2023-04-06 15:23
Closing as a duplicate of #271

**Closed by kevinpalis** 2023-04-06 15:23 UTC
